
"use client";
import React, { useEffect } from "react";
import  Link  from "next/link";
import { usePathname } from 'next/navigation';
import { createPageUrl } from "@/utils/createPageUrl";
// import '@/globals.css
import './globals.css'; // ✅ relative path to the CSS file
// import 'react-vertical-timeline-component/style.min.css';
import {
  Phone,
  MapPin,
  Clock,
  Mail,
  Facebook,
  Instagram,
  Youtube,
  Twitter,
  Menu,
  ChevronDown,
  Calendar
} from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Sheet,
  SheetContent,
  SheetTrigger,
} from "@/components/ui/sheet";
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const navigationItems = [
  { name: "Home", path: "/" },
  { name: "About", path: "About" },
  {
    name: "Services",
    path: "Services",
    submenu: [
      { name: "Engine Repair", path: "enginerepair" },
      { name: "Brake Service", path: "BrakeService" },
      { name: "Diagnostics", path: "Diagnostics" },
      { name: "Electrical Systems", path: "electricalsystem" },
      { name: "Oil Changes", path: "OilChanges" },
      { name: "Wheel & Tire", path: "wheeltire" },
      { name: "Transmission", path: "Transmission" },
      { name: "Air Conditioning", path: "airconditioning" },
      { name: "Preventative Maintenance", path: "PreventativeMaintenance" },
      { name: "Battery Services", path: "BatteryServices" },
      { name: "NY State Inspection", path: "NYStateInspection" },
      { name: "Suspension & Steering", path: "SuspensionSteering" }
    ]
  },
  { name: "Car Care Plans", path: "CarCarePlans" },
  { name: "Reviews", path: "Reviews" },
  { name: "Videos", path: "Videos" },
  { name: "Blog", path: "blog" },
  { name: "Contact", path: "Contact" }
];

const socialLinks = [
  { 
    name: "Facebook", 
    icon: Facebook, 
    url: "https://www.facebook.com/everythingautony/", 
    color: "#1877F2"   // Official Facebook Blue
  },
  { 
    name: "Instagram", 
    icon: Instagram, 
    url: "https://www.instagram.com/everythingautony", 
    color: "linear-gradient(45deg,#F58529,#FEDA77,#DD2A7B,#8134AF,#515BD4)" // Official Instagram Gradient
  },
  { 
    name: "Youtube", 
    icon: Youtube, 
    url: "https://www.youtube.com/@EverythingAutoNY", 
    color: "#FF0000"   // Official YouTube Red
  },
  { 
    name: "Twitter", 
    icon: Twitter, 
    url: "https://x.com/everythngautony", 
    color: "#000000"   // New Twitter (X) Black
  }
];
const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
  const location = usePathname();

  const [mobileMenuOpen, setMobileMenuOpen] = React.useState(false);

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [location]);

  const localBusinessSchema = {
    "@context": "https://schema.org",
    "@type": "AutoRepair",
    "name": "Everything Auto",
    "image": "https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/09d6b1a90_pngglowlogo1.png",
    "@id": "https://everythingauto.com",
    "url": "https://everythingauto.com",
    "telephone": "+1-516-775-9724",
    "email": "everythingautonewyork@gmail.com",
    "address": {
      "@type": "PostalAddress",
      "streetAddress": "980 Washington St",
      "addressLocality": "Franklin Square",
      "addressRegion": "NY",
      "postalCode": "11010",
      "addressCountry": "US"
    },
    "geo": {
      "@type": "GeoCoordinates",
      "latitude": 40.706130,
      "longitude": -73.681120
    },
    "openingHoursSpecification": {
      "@type": "OpeningHoursSpecification",
      "dayOfWeek": [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday"
      ],
      "opens": "08:00",
      "closes": "18:00"
    },
    "sameAs": socialLinks.map(link => link.url)
  };

  return (
            <html lang="en">
            <body className={inter.className} suppressHydrationWarning={true}>
    <div className="min-h-screen bg-white text-gray-900">
      <link rel="icon" type="image/png" href="https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/07eee8b8a_everthinglogo.jpg" />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(localBusinessSchema) }}
      />


      {/* Top Bar */}
      <div 
                                       style={{
        boxShadow:
          "inset 0 -2px 5px rgba(138, 193, 252, 0.44), inset 0 2px 5px rgba(19, 19, 19, 0.6), 0 2px 5px rgba(0, 0, 0, 0.11)",
      }}
      className="bg-gradient-to-b from-blue-800 to-gray-800 text-white border-b border-gray-500 py-3 px-10 sm:px-40 md:px-10 lg:px-10 text-sm">
        <div className="max-w-screen-2xl mx-auto flex justify-between items-center gap-8">
            <div className="flex-1 flex items-center gap-x-8">
                <a href="tel:516-775-9724" className="flex items-center space-x-2 text-white hover:text-blue-300 transition-colors font-semibold">
                  <Phone className="w-4 h-4" />
                  <span>(516) 775-9724</span>
                </a>
                <a href="https://www.google.com/maps/place/980+Washington+St,+Franklin+Square,+NY+11010" target="_blank" rel="noopener noreferrer" className="hidden lg:flex items-center space-x-2 text-white hover:text-blue-200 transition-colors">
                  <MapPin className="w-4 h-4" />
                  <span>980 Washington St, Franklin Square, NY 11010</span>
                </a>
                <a href="mailto:everythingautonewyork@gmail.com" className="hidden xl:flex items-center space-x-2 text-white hover:text-blue-200 transition-colors">
                  <Mail className="w-4 h-4" />
                  <span>everythingautonewyork@gmail.com</span>
                </a>
            </div>
            <div className="flex items-center space-x-4">
                {socialLinks.map(link => (
    <a
      key={link.name}
      href={link.url}
      target="_blank"
      rel="noopener noreferrer"
      className="p-2 rounded-full transition-transform hover:scale-110"
      style={{
        background: link.color,
        boxShadow:
          "inset 0 -2px 3px rgba(255, 255, 255, 0.48), inset 0 2px 2px rgba(19, 19, 19, 0.61)",
      }}
    >
      <link.icon className="w-5 h-5 text-white" />
    </a>
  ))}
            </div>
        </div>
      </div>

      {/* Main Header */}
      <header className="bg-white/70 backdrop-blur-md border-b border-white/70 sticky top-0 z-50">
        <div className="max-w-screen-2xl mx-auto px-1 sm:px-1 lg:px-1">
          <div className="flex items-center justify-between h-28">
            {/* Logo */}
            <Link href='/' className="flex-shrink-0 cursor-pointer">
              <img
                // src="https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/09d6b1a90_pngglowlogo1.png"
                src="/EveryThingAutoLogo.png"
                alt="Everything Auto - Expert Auto Repair in Franklin Square, NY"
                className="header-logo"
              />
            </Link>

            {/* Desktop Navigation - Centered */}
            <nav className="hidden lg:flex items-center justify-center flex-1">
              <div className="flex items-center space-x-6 xl:space-x-8 2xl:space-x-10">
                {navigationItems.map((item) => (
                  <div key={item.name} className="relative group">
                    <Link
                      href={createPageUrl(item.path)}
                      className={`font-semibold transition-colors py-2 flex items-center space-x-1.5 text-sm xl:text-base 2xl:text-lg`}
                    >
                      <span>{item.name}</span>
                      {item.submenu && <ChevronDown className="w-4 h-4 transition-transform duration-300 group-hover:rotate-180" />}
                    </Link>
                    {item.submenu && (
                      <div className="absolute top-full left-1/2 -translate-x-1/2 w-64 bg-white shadow-2xl rounded-lg py-3 opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-300 transform translate-y-4 group-hover:translate-y-2 z-50 border border-[var(--color-border)]">
                        {item.submenu.map((subItem) => (
                          <Link
                            key={subItem.name}
                            href={createPageUrl(subItem.path)}
                            className={
                              `block px-5 py-2.5 transition-colors duration-200text-black hover:text-white hover:bg-[var(--color-primary)]
                              `
                            }
                          >
                            {subItem.name}
                          </Link>
                        ))}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </nav>

            {/* CTA Buttons */}
            <div className="hidden lg:flex items-center space-x-3 xl:space-x-4">
                  <a href="tel:516-775-9724">
                    <Button
                      style={{
                        boxShadow:
                          "inset 0 -2px 5px rgba(249, 195, 195, 0.65), inset 0 2px 5px rgba(19, 19, 19, 0.4), 0 2px 5px rgba(0, 0, 0, 0.11)",
                      }}
                      className="bg-gradient-to-b from-red-600 to-gray-100/10 rounded-lg font-semibold px-4 xl:px-6 py-2 xl:py-3 text-sm xl:text-base flex items-center transform transition-all duration-300 hover:scale-105 hover:shadow-xl">
                      <Phone className="w-4 h-4 mr-1" />
                      CALL NOW
                    </Button>
                  </a>
              <a href="https://myalp.io/nqc45n" target="_blank" rel="noopener noreferrer">
                <Button 
                     style={{
        boxShadow:
          "inset 0 -2px 5px rgba(138, 193, 252, 0.57), inset 0 2px 5px rgba(19, 19, 19, 0.4), 0 2px 5px rgba(0, 0, 0, 0.11)",
      }}
                className="bg-gradient-to-b from-blue-700 to-gray-100/10 font-semibold px-4 xl:px-6 py-2 xl:py-3 rounded-lg text-sm xl:text-base transform transition-all duration-300 hover:scale-105 hover:shadow-xl ">
                  <Calendar className="w-4 h-4 mr-1" />
                  Book Appointment
                </Button>
              </a>
             
            </div>

            {/* Mobile Menu */}
            <div className="lg:hidden">
              <Sheet open={mobileMenuOpen} onOpenChange={setMobileMenuOpen}>
                <SheetTrigger asChild>
                  <Button variant="outline" size="icon">
                    <Menu className="w-6 h-6" />
                  </Button>
                </SheetTrigger>
                <SheetContent className="w-80">
                  <nav className="flex flex-col space-y-2 mt-8">
                    <Accordion type="single" collapsible className="w-full">
                      {navigationItems.map((item) => item.submenu ? (
                        <AccordionItem value={item.name} key={item.name}>
                          <AccordionTrigger className="font-bold text-lg hover:no-underline text-gray-900">{item.name}</AccordionTrigger>
                          <AccordionContent>
                            <div className="flex flex-col space-y-1 pl-4">
                              {item.submenu.map(subItem => (
                                <Link
                                  key={subItem.name}
                                  href={createPageUrl(subItem.path)}
                                  className={
                                    `block py-2 text-gray-600 hover:text-[var(--color-primary)]`
                                  }
                                  onClick={() => setMobileMenuOpen(false)}
                                >
                                  {subItem.name}
                                </Link>
                              ))}
                            </div>
                          </AccordionContent>
                        </AccordionItem>
                      ) : (
                        <Link
                          key={item.name}
                          href={createPageUrl(item.path)}
                          className={`block py-3 font-bold text-lg border-b ${
                            (item.path === "Home" && location === "/") || 
                            (item.path !== "Home" && location.includes(item.path))
                              ? "text-[var(--color-primary)]"
                              : "text-gray-800 hover:text-[var(--color-primary)]"
                          }`}
                          onClick={() => setMobileMenuOpen(false)}
                        >
                          {item.name}
                        </Link>
                      ))}
                    </Accordion>
                  </nav>
                  <div className="mt-8 space-y-3">
                     <a href="tel:516-775-9724" className="w-full block">
                       <Button className="w-full btn-accent font-semibold text-lg py-3 flex items-center justify-center space-x-2">
                         <Phone className="w-5 h-5" />
                         <span>CALL NOW: (516) 775-9724</span>
                       </Button>
                     </a>
                     <a href="https://myalp.io/nqc45n" target="_blank" rel="noopener noreferrer" className="w-full block">
                       <Button className="w-full btn-primary font-semibold text-lg py-3">Book Appointment</Button>
                     </a>
                  </div>
                </SheetContent>
              </Sheet>
            </div>
          </div>
        </div>
      </header>

      <main className="flex-1">{children}</main>

      {/* Footer */}
      <footer className="bg-gray-900 text-white">
        <div className="max-w-screen-xl mx-auto px-4 section-padding">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-12">
            {/* About */}
            <div className="lg:col-span-1 flex flex-col items-center text-center">
              <Link href={createPageUrl("Home")} className="cursor-pointer mb-4">
                <img
                  src="https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/09d6b1a90_pngglowlogo1.png"
                  alt="Everything Auto Logo"
                  className="footer-logo"
                />
              </Link>
              <p className="text-gray-400 text-sm">
                Franklin Square&apos;s trusted family-owned auto repair shop since 2008. We are committed to providing honest, high-quality service for all makes and models.
              </p>
            </div>

            {/* Services Links */}
            <div>
              <h4 className="text-lg font-semibold mb-4 text-white uppercase tracking-wider">Our Services</h4>
              <ul className="space-y-3">
                <li><Link href={createPageUrl("EngineRepair")} className="text-gray-300 hover:text-white transition-colors">Engine Repair</Link></li>
                <li><Link href={createPageUrl("BrakeService")} className="text-gray-300 hover:text-white transition-colors">Brake Service</Link></li>
                <li><Link href={createPageUrl("Diagnostics")} className="text-gray-300 hover:text-white transition-colors">Diagnostics</Link></li>
                <li><Link href={createPageUrl("OilChanges")} className="text-gray-300 hover:text-white transition-colors">Oil Changes</Link></li>
                <li><Link href={createPageUrl("NYStateInspection")} className="text-gray-300 hover:text-white transition-colors">NY State Inspection</Link></li>
              </ul>
            </div>

            {/* Contact Info */}
            <div>
              <h4 className="text-lg font-semibold mb-4 text-white uppercase tracking-wider">Contact Info</h4>
              <ul className="space-y-4 text-gray-300">
                <li className="flex items-start space-x-3">
                  <MapPin className="w-5 h-5 text-[var(--color-primary)] mt-1 flex-shrink-0" />
                  <a href="https://www.google.com/maps/place/980+Washington+St,+Franklin+Square,+NY+11010" target="_blank" rel="noopener noreferrer" className="hover:text-white transition-colors">
                    980 Washington St<br/>Franklin Square, NY 11010
                  </a>
                </li>
                 <li className="flex items-start space-x-3">
                  <Phone className="w-5 h-5 text-[var(--color-primary)] mt-1 flex-shrink-0" />
                  <a href="tel:516-775-9724" className="hover:text-white transition-colors">(516) 775-9724</a>
                </li>
                <li className="flex items-start space-x-3">
                  <Mail className="w-5 h-5 text-[var(--color-primary)] mt-1 flex-shrink-0" />
                  <a href="mailto:everythingautonewyork@gmail.com" className="hover:text-white transition-colors break-all">everythingautonewyork@gmail.com</a>
                </li>
              </ul>
            </div>

            {/* Business Hours */}
            <div>
              <h4 className="text-lg font-semibold mb-4 text-white uppercase tracking-wider">Business Hours</h4>
              <ul className="space-y-3 text-gray-300">
                <li>
                  <a href="https://myalp.io/nqc45n" target="_blank" rel="noopener noreferrer" className="hover:text-white transition-colors cursor-pointer">
                    Mon - Sat: 8:00 AM - 6:00 PM
                  </a>
                </li>
                <li>Sunday: Closed</li>
              </ul>
              <div className="mt-6 flex space-x-4">
                          {socialLinks.map(link => (
    <a
      key={link.name}
      href={link.url}
      target="_blank"
      rel="noopener noreferrer"
      className="p-2 rounded-full transition-transform hover:scale-110"
      style={{
        background: link.color,
        boxShadow:
          "inset 0 -3px 6px rgba(255, 255, 255, 0.4), inset 0 3px 6px rgba(19, 19, 19, 0.61), 0 3px 7px rgba(0, 0, 0, 0.11)",
      }}
    >
      <link.icon className="w-5 h-5 text-white" />
    </a>
  ))}
              </div>
            </div>
          </div>
          <div className="border-t border-gray-700 mt-16 pt-8 text-center text-gray-500 text-sm">
            <span>&copy; {new Date().getFullYear()} Everything Auto. All Rights Reserved.</span>
          </div>
        </div>
      </footer>
    </div>
    </body>
    </html>
  );
}

